#!/usr/bin/env bash

export DB_USER='root'
export DB_PASSWORD='P2g7QIBT3ID'
export DB_URL='agestech.cqtwi4ijanzf.us-east-2.rds.amazonaws.com'
export DB_NAME='development'
export SERVER_NAME='localhost'
export PYTHONUNBUFFERED=True
